// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | RichTextSlice
  | TestimonialsSlice
  | TestimonialPricingSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *TestimonialPricing → Default → Primary*
 */
export interface TestimonialPricingSliceDefaultPrimary {
  /**
   * Testimonial Quote field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the testimonial quote...
   * - **API ID Path**: testimonial_pricing.default.primary.testimonial_quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial_quote: prismic.RichTextField;

  /**
   * Testimonial Avatar field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_pricing.default.primary.testimonial_avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  testimonial_avatar: prismic.ImageField<never>;

  /**
   * Testimonial Author field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name
   * - **API ID Path**: testimonial_pricing.default.primary.testimonial_author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  testimonial_author: prismic.KeyTextField;

  /**
   * Testimonial Subtitle field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author subtitle or description
   * - **API ID Path**: testimonial_pricing.default.primary.testimonial_subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  testimonial_subtitle: prismic.KeyTextField;

  /**
   * Pricing Tagline field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tagline
   * - **API ID Path**: testimonial_pricing.default.primary.pricing_tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pricing_tagline: prismic.KeyTextField;

  /**
   * Pricing Heading field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the pricing heading...
   * - **API ID Path**: testimonial_pricing.default.primary.pricing_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pricing_heading: prismic.RichTextField;

  /**
   * Pricing Description field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter the pricing description...
   * - **API ID Path**: testimonial_pricing.default.primary.pricing_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  pricing_description: prismic.RichTextField;

  /**
   * Plan Name field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Free — Just explore
   * - **API ID Path**: testimonial_pricing.default.primary.plan_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  plan_name: prismic.KeyTextField;

  /**
   * Price Amount field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., $0
   * - **API ID Path**: testimonial_pricing.default.primary.price_amount
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price_amount: prismic.KeyTextField;

  /**
   * Price Period field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., /mo
   * - **API ID Path**: testimonial_pricing.default.primary.price_period
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price_period: prismic.KeyTextField;

  /**
   * Yearly Price field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., or $0 yearly
   * - **API ID Path**: testimonial_pricing.default.primary.yearly_price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  yearly_price: prismic.KeyTextField;

  /**
   * CTA Button field in *TestimonialPricing → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_pricing.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  cta_button: prismic.ContentRelationshipField;
}

/**
 * Default variation for TestimonialPricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialPricingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialPricingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialPricing*
 */
type TestimonialPricingSliceVariation = TestimonialPricingSliceDefault;

/**
 * TestimonialPricing Shared Slice
 *
 * - **API ID**: `testimonial_pricing`
 * - **Description**: A combined testimonial and pricing section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialPricingSlice = prismic.SharedSlice<
  "testimonial_pricing",
  TestimonialPricingSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Image field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Customer name...
   * - **API ID Path**: testimonials.default.primary.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Review field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Customer review...
   * - **API ID Path**: testimonials.default.primary.testimonials[].review
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review: prismic.RichTextField;

  /**
   * Company field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company name...
   * - **API ID Path**: testimonials.default.primary.testimonials[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Rating field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section heading...
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: A testimonials section displaying customer reviews with images, names, companies, and ratings
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TestimonialPricingSlice,
      TestimonialPricingSliceDefaultPrimary,
      TestimonialPricingSliceVariation,
      TestimonialPricingSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
