// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | RichTextSlice
  | TestimonialsSlice
  | PricingCardSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Primary content in *PricingCard → Default → Primary*
 */
export interface PricingCardSliceDefaultPrimary {
  /**
   * Testimonial Quote field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter testimonial quote
   * - **API ID Path**: pricing_card.default.primary.testimonialQuote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonialQuote: prismic.RichTextField;

  /**
   * Testimonial Avatar field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing_card.default.primary.testimonialAvatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  testimonialAvatar: prismic.ImageField<never>;

  /**
   * Testimonial Name field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter name
   * - **API ID Path**: pricing_card.default.primary.testimonialName
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  testimonialName: prismic.KeyTextField;

  /**
   * Testimonial Subtitle field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter subtitle
   * - **API ID Path**: pricing_card.default.primary.testimonialSubtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  testimonialSubtitle: prismic.KeyTextField;

  /**
   * Tagline field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter tagline
   * - **API ID Path**: pricing_card.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Heading field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading
   * - **API ID Path**: pricing_card.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: pricing_card.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Plan Name field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter plan name
   * - **API ID Path**: pricing_card.default.primary.planName
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  planName: prismic.KeyTextField;

  /**
   * Price field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter price (e.g., $0/mo)
   * - **API ID Path**: pricing_card.default.primary.price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * Price Suffix field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter price suffix (e.g., or $0 yearly)
   * - **API ID Path**: pricing_card.default.primary.priceSuffix
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  priceSuffix: prismic.KeyTextField;

  /**
   * Pricing CTA field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter CTA link
   * - **API ID Path**: pricing_card.default.primary.pricingCta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  pricingCta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Bottom Heading field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter bottom heading
   * - **API ID Path**: pricing_card.default.primary.bottomHeading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bottomHeading: prismic.RichTextField;

  /**
   * Bottom Description field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter bottom description
   * - **API ID Path**: pricing_card.default.primary.bottomDescription
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bottomDescription: prismic.RichTextField;

  /**
   * Bottom CTA field in *PricingCard → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter bottom CTA link
   * - **API ID Path**: pricing_card.default.primary.bottomCta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  bottomCta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for PricingCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PricingCard*
 */
type PricingCardSliceVariation = PricingCardSliceDefault;

/**
 * PricingCard Shared Slice
 *
 * - **API ID**: `pricing_card`
 * - **Description**: A pricing slice with testimonial, pricing card, and CTA sections
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingCardSlice = prismic.SharedSlice<
  "pricing_card",
  PricingCardSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Testimonials*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialsItem {
  /**
   * Image field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Customer name...
   * - **API ID Path**: testimonials.default.primary.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Review field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Customer review...
   * - **API ID Path**: testimonials.default.primary.testimonials[].review
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review: prismic.RichTextField;

  /**
   * Company field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company name...
   * - **API ID Path**: testimonials.default.primary.testimonials[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Rating field in *Testimonials → Default → Primary → Testimonials*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section heading...
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Testimonials field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialsItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: A testimonials section displaying customer reviews with images, names, companies, and ratings
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      PricingCardSlice,
      PricingCardSliceDefaultPrimary,
      PricingCardSliceVariation,
      PricingCardSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialsItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
